In [41]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
import pickle

In [42]:
print("MRidul")

MRidul

In [43]:
## importing the data
data = pd.read_csv("synthetic_student_performance.csv")
data.head(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,1,3,16,13,0,2,0,0,0,0,3.158425,1
1,1002,18,1,2,0,17,28,0,2,1,1,1,0,2.794655,2
2,1003,15,1,0,1,13,18,1,4,0,0,0,1,3.774847,0
3,1004,17,1,0,3,6,4,0,3,1,0,0,0,3.040574,1
4,1005,17,0,1,2,6,20,0,4,0,0,0,0,3.382310,1
5,1006,18,0,3,4,13,23,1,2,1,0,1,0,4.000000,0
6,1007,15,1,0,3,14,25,0,2,1,0,1,1,3.009268,1
7,1008,15,0,0,4,11,8,0,3,0,0,1,1,4.000000,0
8,1009,17,1,1,1,11,23,0,2,0,0,0,0,3.944525,0
9,1010,16,1,3,4,7,11,0,3,0,1,1,1,2.735138,2

In [44]:
data = data.drop(["StudentID"],axis=1)
data.head()

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,17,1,1,3,16,13,0,2,0,0,0,0,3.158425,1
1,18,1,2,0,17,28,0,2,1,1,1,0,2.794655,2
2,15,1,0,1,13,18,1,4,0,0,0,1,3.774847,0
3,17,1,0,3,6,4,0,3,1,0,0,0,3.040574,1
4,17,0,1,2,6,20,0,4,0,0,0,0,3.382310,1

In [45]:
## ohe hot encoding the ethnicity 
ohe_ethn = OneHotEncoder()
eth_encoder = ohe_ethn.fit_transform(data[['Ethnicity']])

In [46]:
eth_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5000 stored elements and shape (5000, 4)>

In [47]:
ohe_ethn.get_feature_names_out(['Ethnicity'])

array(['Ethnicity_0', 'Ethnicity_1', 'Ethnicity_2', 'Ethnicity_3'],
      dtype=object)

In [48]:
ethn_encoded = pd.DataFrame(eth_encoder.toarray(),columns=ohe_ethn.get_feature_names_out(['Ethnicity']))
ethn_encoded

      Ethnicity_0  Ethnicity_1  Ethnicity_2  Ethnicity_3
0             0.0          1.0          0.0          0.0
1             0.0          0.0          1.0          0.0
2             1.0          0.0          0.0          0.0
3             1.0          0.0          0.0          0.0
4             0.0          1.0          0.0          0.0
...           ...          ...          ...          ...
4995          0.0          0.0          0.0          1.0
4996          0.0          1.0          0.0          0.0
4997          0.0          1.0          0.0          0.0
4998          0.0          0.0          1.0          0.0
4999          0.0          0.0          1.0          0.0

[5000 rows x 4 columns]

In [49]:
data = data.drop(['Ethnicity'],axis=1)

In [50]:
data = pd.concat([data,ethn_encoded],axis=1)
data.head()

,Age,Gender,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass,Ethnicity_0,Ethnicity_1,Ethnicity_2,Ethnicity_3
0,17,1,3,16,13,0,2,0,0,0,0,3.158425,1,0.0,1.0,0.0,0.0
1,18,1,0,17,28,0,2,1,1,1,0,2.794655,2,0.0,0.0,1.0,0.0
2,15,1,1,13,18,1,4,0,0,0,1,3.774847,0,1.0,0.0,0.0,0.0
3,17,1,3,6,4,0,3,1,0,0,0,3.040574,1,1.0,0.0,0.0,0.0
4,17,0,2,6,20,0,4,0,0,0,0,3.382310,1,0.0,1.0,0.0,0.0

In [51]:
## saving the encoded file using pickle
with open('ethnicity_encoder.pkl','wb') as file:
    pickle.dump(ohe_ethn,file)

In [52]:
x = data.drop(['GPA','GradeClass'],axis=1)
y = data['GPA']

In [53]:
## train test split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [54]:
## scaling the features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [55]:
print(x_train)

[[ 1.33222518 -1.01969389 -1.68619785 ... -0.49882785  2.01100378
  -0.32493568]
 [ 0.44451891  0.98068647 -0.06543817 ... -0.49882785 -0.49726411
  -0.32493568]
 [-1.33089362 -1.01969389 -0.06543817 ... -0.49882785  2.01100378
  -0.32493568]
 ...
 [ 0.44451891 -1.01969389  0.74494167 ... -0.49882785 -0.49726411
  -0.32493568]
 [ 1.33222518 -1.01969389  1.55532151 ...  2.00469962 -0.49726411
  -0.32493568]
 [ 1.33222518  0.98068647 -0.87581801 ... -0.49882785  2.01100378
  -0.32493568]]

In [56]:
## saving the standaard scaler

with open('Standard_Scaler.pkl','wb') as file:
    pickle.dump(StandardScaler,file)

ANN IMPLEMENTATIOn

In [57]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [58]:
print(x_train.shape[1])

15

In [59]:
## building the ann 

model = Sequential([
    Dense(32,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(16,activation='relu'),
    Dense(1,activation='linear')
])

c:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [60]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,057 (4.13 KB)

 Trainable params: 1,057 (4.13 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.Huber(delta=1.0)

In [62]:
model.compile(optimizer=opt,loss=loss,metrics=['mae'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [63]:
## setup tensorboard
log_dir = "log/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [64]:
## early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [65]:
## training the model 
history = model.fit(
    x_train,y_train,validation_data = (x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]

)

Epoch 1/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2981 - mae: 0.6368 - val_loss: 0.1639 - val_mae: 0.4853
Epoch 2/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1602 - mae: 0.4767 - val_loss: 0.1532 - val_mae: 0.4741
Epoch 3/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1489 - mae: 0.4607 - val_loss: 0.1504 - val_mae: 0.4636
Epoch 4/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1436 - mae: 0.4532 - val_loss: 0.1615 - val_mae: 0.4752
Epoch 5/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1421 - mae: 0.4511 - val_loss: 0.1475 - val_mae: 0.4595
Epoch 6/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1390 - mae: 0.4442 - val_loss: 0.1603 - val_mae: 0.4849
Epoch 7/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1407 - mae: 0.4483 - val_loss: 0.1521 - val_mae: 0.4665
Epoch 8/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1398 - mae: 0.4479 - val_loss: 0.1463 - val_mae: 0.4576
Epoch 9/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1340 - mae: 0.4402 - val_loss: 0.1523 - val_mae: 0.4719
Epoch 10/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1354 - mae: 0.4416 - val_loss: 0.1587 - val_mae: 0.4859
Epoch 11/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1348 - mae: 0.4410 - val_loss: 0.1436 - val_mae: 0.4651
Epoch 12/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1360 - mae: 0.4417 - val_loss: 0.1472 - val_mae: 0.4666
Epoch 13/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1341 - mae: 0.4396 - val_loss: 0.1430 - val_mae: 0.4563
Epoch 14/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1327 - mae: 0.4361 - val_loss: 0.1505 - val_mae: 0.4708
Epoch 15/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1302 - mae: 0.4330 - val_loss: 0.1420 - val_mae: 0.4577
Epoch 16/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1314 - mae: 0.4363 - val_loss: 0.1456 - val_mae: 0.4595
Epoch 17/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1287 - mae: 0.4319 - val_loss: 0.1430 - val_mae: 0.4522
Epoch 18/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1302 - mae: 0.4323 - val_loss: 0.1426 - val_mae: 0.4625
Epoch 19/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1302 - mae: 0.4326 - val_loss: 0.1475 - val_mae: 0.4679
Epoch 20/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1272 - mae: 0.4277 - val_loss: 0.1540 - val_mae: 0.4791
Epoch 21/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1285 - mae: 0.4293 - val_loss: 0.1466 - val_mae: 0.4648
Epoch 22/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1282 - mae: 0.4280 - val_loss: 0.1433 - val_mae: 0.4606
Epoch 23/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1269 - mae: 0.4264 - val_loss: 0.1457 - val_mae: 0.4598
Epoch 24/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1272 - mae: 0.4279 - val_loss: 0.1634 - val_mae: 0.4926
Epoch 25/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1279 - mae: 0.4293 - val_loss: 0.1474 - val_mae: 0.4557

In [66]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [67]:
## load tensorboard extension

%load_ext tensorboard

In [69]:
%tensorboard --logdir log/fit20260613-123937

Reusing TensorBoard on port 6006 (pid 8760), started 0:00:42 ago. (Use '!kill 8760' to kill it.)